version: '3.9'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    networks:
      - test-network

  nodejs:
    restart: on-failure
    build: ./
    ports:
      - '5000:5000'
    networks:
      - test-network

networks:
  test-network:
    name: test-network
    driver: bridge